export { CopilotChat } from './CopilotChat'
export { CopilotPanel } from './CopilotPanel'
export { useCopilotChat } from './useCopilotChat'
export { copilotSkills, matchSkill } from './skills/registry'
export type { CopilotSkill, CopilotTool } from './skills/types'
