#!/bin/bash

#BSUB -J AF3-05
#BSUB -q gpu-bme-liz
#BSUB -n 1
#BSUB -gpu "num=1"
#BSUB -R "span[ptile=1]"
#BSUB -o %J.out
#BSUB -e %J.err

module purge
module load  cuda/12.6
source /share/apps/anaconda3/bin/activate /share/apps/anaconda3/envs/alphafold3-v3.0.1

##export XLA_PYTHON_CLIENT_ALLOCATOR=platform
export XLA_FLAGS="--xla_gpu_enable_triton_gemm=false"
export XLA_PYTHON_CLIENT_PREALLOCATE=true
export XLA_CLIENT_MEM_FRACTION=0.95

bash tasks_bash > $LSB_JOBID.log 2>&1
