#!/bin/bash

#BSUB -J RFdiffusion
#BSUB -q 4v100-16-e5
#BSUB -n 1
#BSUB -gpu "num=1"
#BSUB -R "span[ptile=1]"
#BSUB -o %J.out
#BSUB -e %J.err

source activate /work/bme-liz/miniconda3/envs/SE3nv-gpu

/work/bme-liz/software/RFdiffusion/scripts/run_inference.py \
inference.input_pdb=./BamA-open.pdb \
'contigmap.contigs=[A1-810/0 60-100]' \
'ppi.hotspot_res=[A]' \
inference.num_designs=50 \
inference.output_prefix=./binder \
> $LSB_JOBID.log 2>&1
